#!/bin/bash
#
#  allmnd The ALLMN Core server.
#
#
# chkconfig: 345 80 20
# description: allmnd
# processname: allmnd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/allmnd, see below
if [ -f /etc/sysconfig/allmnd ]; then
        . /etc/sysconfig/allmnd
fi

RETVAL=0

prog=allmnd
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/allmnd
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/allmnd}

# allmnd defaults to /usr/bin/allmnd, override with BITCOIND_BIN
allmnd=${BITCOIND_BIN-/usr/bin/allmnd}

# allmnd opts default to -disablewallet, override with BITCOIND_OPTS
allmnd_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $allmnd $allmnd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
